### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by kingtastic** [CS-at-GA/APCSP-02-ImageManipulations#6]
I tried to make three new image filters, but none of my new ones are working. They all return that the property undefined cannot be read.

My project code is here: https://replit.com/@ga-apcsp-2223/Image-Manipulation-kingtastic#README.md
Error in console: https://gyazo.com/c261e4a35238a36dff910e62123edfaf (no filter is in effect)

Remember that you can attach files to this issue request.

**Comment by gajoswald** [comment]
The problem, I think, is that you're not returning the new image. If you look at the structure of the other filters it is basically: 

```javascript
// get ready by making a new image to work on
// make the changes on the new image using the existing image
// return the new image
```

That should fix the issues, though there may be others.
